Repository tektoncd/friends, pull requests merged in 2019-07, with the labels that each got.

#1 Initial commit with boilerplate files.
  CONTRIBUTING.md
  OWNERS
  README.md
  code-of-conduct.md
Labels: lgtm, size/L

#3 Added Red Hat to Tekton friends
  redhat/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2 Create readme.md for google
  google/readme.md
Labels: approved, lgtm, size/XS

#4 Added Alibaba to Tekton friends
  alibaba/readme.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#5 Add CloudBees readme
  cloudbees/readme.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#6 Add IBM readme
  ibm/readme.md
Labels: approved, lgtm, size/XS

#7 Update OWNERS to include skaegi/me
  OWNERS
Labels: approved, lgtm, size/XS

#8 add triggermesh
  triggermesh/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS
